name: AllTool Project

on:
    pull_request:
        branches:
            - Stable

jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: python:3.13
        steps:
            - user: actions/checkout@v3
            with:
                python-version: '3.13'
            - run: pip install -r requirements.txt
            - run: python3 AllTool.py
            - run: echo "AllTool Test Completed"
            - run: python3 AllToolInstaller.py
